trigger:
- master

resources:
- repo: self

name: $(major).$(minor)$(Rev:.r)

variables:
  patch: $[counter(variables['minor'], 0)]
  imageTag: $(major).$(minor).$(patch)

stages:
- stage:
  displayName: Version
  jobs:
  - job: Version
    steps:
      - bash: |
           echo "##vso[build.updatebuildnumber]$(major).$(minor).$(patch)"
        name: SetMasterBuildName
- stage: BuildAndTest
  displayName: Build & Test
  jobs:
  - job: ApiService
    displayName: ApiService
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        command: 'build'
        workingDirectory: $(System.DefaultWorkingDirectory)
        configuration: $(buildConfiguration)
    - task: DotNetCoreCLI@2
      displayName: "dotnet test"
      inputs:
        command: 'test'
        workingDirectory: $(System.DefaultWorkingDirectory)
        arguments: '--collect "Code coverage"'
    - task: PublishTestResults@2
      displayName: Publish .NET Core test results and coverage
      condition: succeededOrFailed()
      inputs:
        testRunner: VSTest
        testResultsFiles: '**/*.trx'
- stage: Deploy
  displayName: Build and deploy Docker image
  jobs:
  - job: BuildApiService
    displayName: Build ApiService image
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        repository: 'dotnetrulez/carrentalapi'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'